name: Deploy Serverless

on:
    pull_request:
      types: [opened, synchronize, reopened]
    push:
      branches:
        - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'pull_request' && 'dev' || 'prod' }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set environment
        run: echo "STAGE=${{ github.event_name == 'pull_request' && 'dev' || 'prod' }}" >> $GITHUB_ENV

      - name: Configure AWS Profile
        run: |
          mkdir -p ~/.aws
          echo "[main]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[main]" > ~/.aws/config
          echo "region=us-west-2" >> ~/.aws/config
          echo "output=json" >> ~/.aws/config

      - name: Deploy to AWS
        env:
          GOOGLE_CLIENT_ID: ${{ vars.GOOGLE_CLIENT_ID }}
        run: npx serverless deploy --stage ${{ env.STAGE }} --aws-profile main -r us-west-2

      - name: Get API URL
        id: api
        run: |
          API_URL=$(npx serverless info --stage ${{ env.STAGE }} --aws-profile main -r us-west-2 | grep "endpoint:" | cut -d' ' -f2)
          echo "API_URL=$API_URL" >> $GITHUB_ENV
          echo "API_URL=$API_URL" >> $GITHUB_OUTPUT

